// USER
export const USER_UPDATE = 'USER_UPDATE'
export const USER_RESET = 'USER_RESET'

// SETTINGS
export const USER_SETTINGS_UPDATE_LANGUAGE = 'USER_SETTINGS_UPDATE_LANGUAGE'

// POSTS
export const POST_UPDATE_LIST = 'POST_UPDATE_LIST'
